<?php
$array = array(
		  'I LOVE RADIO' => 'http://stream01.iloveradio.de/iloveradio1.mp3',
		  'I LOVE 2 DANCE' => 'http://stream01.iloveradio.de/iloveradio2.mp3',
		  'I LOVE TOP 100 CHARTS' => 'htt://stream01.iloveradio.de/iloveradio9.mp3',
		  "#original" => "https://listen.reyfm.de/original_128kbps.mp3",
		  "#nightlife" => "https://listen.reyfm.de/nightlife_128kbps.mp3",
		  "#raproyal" => "https://listen.reyfm.de/raproyal_128kbps.mp3",
		  "#summerjam" => "https://listen.reyfm.de/summerjam_128kbps.mp3",
		  "#underground" => "https://listen.reyfm.de/underground_128kbps.mp3",
		  "#hitsonly" => "https://listen.reyfm.de/hitsonly_128kbps.mp3",
		  "#gaming" => "https://listen.reyfm.de/gaming_128kbps.mp3",
		  "#houseparty" => "https://listen.reyfm.de/houseparty_128kbps.mp3",
		  "#chillout" => "https://listen.reyfm.de/chillout_128kbps.mp3",
		  "#exclusive" => "https://listen.reyfm.de/exclusive_128kbps.mp3",
		  "#dancehall" => "https://listen.reyfm.de/dancehall_128kbps.mp3",
		  "#mashup" => "https://listen.reyfm.de/mashup_128kbps.mp3",
		  "#warzone" => "https://listen.reyfm.de/warzone_128kbps.mp3",
		  "#djradio" => "https://listen.reyfm.de/djradio_128kbps.mp3",
		  "#oldschool" => "https://listen.reyfm.de/oldschool_128kbps.mp3",
		  "#mainstage" => "https://listen.reyfm.de/mainstage_128kbps.mp3",
		  "#charts" => "https://listen.reyfm.de/charts_128kbps.mp3",
		  "iLoveRadio" => "http://stream01.ilovemusic.de/iloveradio1.mp3",
		  "iLove2Dance" => "http://stream01.ilovemusic.de/iloveradio2.mp3",
		  "iLoveDeutschrap" => "http://stream01.ilovemusic.de/iloveradio6.mp3",
		  "iLoveMashup" => "http://stream01.ilovemusic.de/iloveradio5.mp3",
		  "iLoveMusicAndChill" => "http://stream01.ilovemusic.de/iloveradio10.mp3",
		  "iLoveTheBattle" => "http://stream01.ilovemusic.de/iloveradio3.mp3",
		  "#original" => "https://synexitfm.stream.laut.fm => 8080/synexitfm",
		  "#nightlife" => "https://synexitfmrap.stream.laut.fm/synexitfmrap",
		  "#charts" => "https://synexitfm80er.stream.laut.fm => 8080/synexitfm80er",
		  "Alles Radio" => "http://stream.laut.fm/alles-radio",
		  "Alles Chill" => "http://stream.laut.fm/alles-chill",
		  "Alles Dance" => "http://stream.laut.fm/alles-dance",
		  "Alles Techno" => "http://stream.laut.fm/alles-techno",
		  "Alles Hardstyle" => "http://stream.laut.fm/alles-hardstyle",
		  "Alles Klub" => "http://stream.laut.fm/alles-klub",
);

echo json_encode($array);
